// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa3LKo6H2Ya_GgAj6tN7flwTTGKEupSZg',
    appId: '1:1030232455864:web:60b7093e7754c43256124d',
    messagingSenderId: '1030232455864',
    projectId: 'repository-41ffb',
    authDomain: 'repository-41ffb.firebaseapp.com',
    storageBucket: 'repository-41ffb.appspot.com',
    measurementId: 'G-0SN7CNPFPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQIa8kfU_H9xnhFboY6ictrcSBawOYpZU',
    appId: '1:1030232455864:android:698287beb6c87ed956124d',
    messagingSenderId: '1030232455864',
    projectId: 'repository-41ffb',
    storageBucket: 'repository-41ffb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaERFZQ-XVSSn5uxa5aIQIBnXybbvQAsg',
    appId: '1:1030232455864:ios:565db1d43543a32456124d',
    messagingSenderId: '1030232455864',
    projectId: 'repository-41ffb',
    storageBucket: 'repository-41ffb.appspot.com',
    iosBundleId: 'com.example.repository',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaERFZQ-XVSSn5uxa5aIQIBnXybbvQAsg',
    appId: '1:1030232455864:ios:565db1d43543a32456124d',
    messagingSenderId: '1030232455864',
    projectId: 'repository-41ffb',
    storageBucket: 'repository-41ffb.appspot.com',
    iosBundleId: 'com.example.repository',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa3LKo6H2Ya_GgAj6tN7flwTTGKEupSZg',
    appId: '1:1030232455864:web:92ee0c89b2baa6e356124d',
    messagingSenderId: '1030232455864',
    projectId: 'repository-41ffb',
    authDomain: 'repository-41ffb.firebaseapp.com',
    storageBucket: 'repository-41ffb.appspot.com',
    measurementId: 'G-42PHE61K2M',
  );
}
